server:
  ssl:
    key-store: classpath:springboot.p12
    key-store-password: password
    key-store-type: pkcs12
    key-alias: springboot
    key-password: password
  port: 8443

spring:
  jpa:
    hibernate:
      ddl-auto: update
      #show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: jdbc:mysql://localhost:3306/capstone
    username: baseUser!
    password: basePassword1!
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  security:
    user:
      name: user
      password: pass
    oauth2:
      client:
        registration:
          google:
            clientId: 911436566286-36r6uc7oavbrmqcmn7b2ijo3q34mn1gi.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile
  mail:
    host: mail.privateemail.com
    port: 587
    username: donotreply@doctracker.org
    password: S22WhatsUpDocCapstone@
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true